### ISSUE TITLE
Update Litemoretica using this.

### ISSUE THREAD

**Issue by AntonyPapav** [Earthcomputer/litemoretica#11]
I have commented this on my previous issue but it was closed so the notification might not have been sent.

This is an unofficial build of litematica made by a supporter. This supporter has also updated malilib. I have tested it and they work perfectly so perhaps it's possible to use it to update Litemoretica to 1.20.6. It doesn't have to be a full release but it could be an alpha/beta update of the mod.

https://github.com/sakura-ryoko/litematica
https://github.com/sakura-ryoko/malilib

**Comment by Earthcomputer** [comment]
I saw your other comment. But I would like to support the official litematica port:
- masa might change something for the official port making the speculative port of litemoretica incompatible with it.
- The build requires the project to be on curseforge.
