### ISSUE TITLE
not working for 1.20

### ISSUE THREAD

**Issue by Dabbpool** [Earthcomputer/litemoretica#2]
it says it supports 1.20-1.21 but then the version says mc1.20.1-1.2.1 and doesn't work for 1.20 
[ForkJoinPool-1-worker-3/WARN]: Mod litemoretica uses the version mc1.20.1-1.2.1 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'mc1'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

**Comment by Earthcomputer** [comment]
How exactly doesn't it work?
