### ISSUE TITLE
1.20.1 crash on opening inventory

### ISSUE THREAD

**Issue by Pi3tro88** [Earthcomputer/litemoretica#3]
[crash-2023-07-24_11.56.21-client.txt](https://github.com/Earthcomputer/litemoretica/files/12144944/crash-2023-07-24_11.56.21-client.txt)
![image](https://github.com/Earthcomputer/litemoretica/assets/88508843/fa8e8b42-b123-4639-a503-f3152688d0aa)

**Comment by Earthcomputer** [comment]
Fixed in latest version
