### ISSUE TITLE
Crash when trying paste big structure

### ISSUE THREAD

**Issue by Rozbiynk** [Earthcomputer/litemoretica#4]
https://mclo.gs/s3u8qRa

**Comment by Rozbiynk** [comment]
litemoretica also installed on server

**Comment by Earthcomputer** [comment]
Seems to have occurred because the litematic had only 1 block type in it.

**Comment by Rozbiynk** [comment]
now it crashes immediately lol
https://mclo.gs/w8kBdM8

**Comment by Rozbiynk** [comment]
![изображение](https://github.com/Earthcomputer/litemoretica/assets/95433246/05454c2b-0357-4515-8214-b050c04f3977)
![изображение](https://github.com/Earthcomputer/litemoretica/assets/95433246/731752c5-f265-4f0f-a763-bf6c970b9511)

**Comment by Rozbiynk** [comment]
just one difference between versions

**Comment by Rozbiynk** [comment]
that's what my host saying
![изображение](https://github.com/Earthcomputer/litemoretica/assets/95433246/d0870199-f244-47d7-914b-b67b00e27c04)

**Comment by Earthcomputer** [comment]
@Rozbiynk did you try the latest commit?

**Comment by Rozbiynk** [comment]
yea, I compile latest changes

**Comment by Earthcomputer** [comment]
@Rozbiynk are you sure? Because the latest commit should have fixed it crashing on every schematic. You need to re-fetch the latest commit.

**Comment by Rozbiynk** [comment]
okay, i try to re-download it

**Comment by thojo0** [comment]
I compiled it and tested.
Minecraft isn't crashing anymore, but I'm getting disconnected from the server with this message:
![grafik](https://github.com/Earthcomputer/litemoretica/assets/53666000/4b9a2c96-dec1-4311-9ddb-256009311143)
The size varyes between different builds.

**Comment by thojo0** [comment]
Ok, sorry. After also putting it on the Server its working fine.
I only had some problems, after pasting, that chunks didn't appear and I had to rejoin. After that they appear.
